version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://agenda:agenda123@db:5432/agenda_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - agenda-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - agenda-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=agenda
      - POSTGRES_PASSWORD=agenda123
      - POSTGRES_DB=agenda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agenda-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - agenda-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: 